# bee/academy/questions.py

QUESTIONS = [
    {
        "id": "q_cdi_001",
        "topic": "Renda Fixa",
        "difficulty": 1,
        "question": "Um CDB 120% do CDI tende a render mais que a poupança?",
        "options": ["Não", "Sim", "Igual", "Só se for acima de 200%"],
        "answer": 1,
        "explanation": "Na maioria dos cenários, 120% do CDI rende bem acima da poupança (que tem regra própria e costuma render menos).",
    },
    {
        "id": "q_reserva_001",
        "topic": "Planejamento",
        "difficulty": 1,
        "question": "Reserva de emergência idealmente deve ficar em qual tipo de investimento?",
        "options": ["Alta volatilidade", "Baixa liquidez", "Alta liquidez e baixo risco", "Ações de crescimento"],
        "answer": 2,
        "explanation": "Reserva é para imprevistos: precisa de liquidez (resgate rápido) e baixo risco (ex.: Tesouro Selic, CDB liquidez diária).",
    },
    {
        "id": "q_ipca_001",
        "topic": "Renda Fixa",
        "difficulty": 2,
        "question": "Tesouro IPCA+ é mais associado a qual objetivo?",
        "options": ["Proteção contra inflação no longo prazo", "Ganhos rápidos em 1 semana", "Reserva de emergência", "Evitar imposto sempre"],
        "answer": 0,
        "explanation": "Tesouro IPCA+ é usado para proteger poder de compra no longo prazo (inflação + juros reais).",
    },
    {
        "id": "q_etf_001",
        "topic": "Renda Variável",
        "difficulty": 1,
        "question": "Qual vantagem comum de um ETF para iniciantes?",
        "options": ["Concentração em 1 ação", "Diversificação automática", "Isenção total de imposto", "Sem risco de oscilação"],
        "answer": 1,
        "explanation": "ETF geralmente dá diversificação automática porque representa uma cesta de ativos/índice.",
    },
    {
        "id": "q_fii_001",
        "topic": "FIIs",
        "difficulty": 2,
        "question": "Um FII pode cair de preço mesmo pagando dividendos mensais?",
        "options": ["Não, dividendos impedem queda", "Sim, preço oscila no mercado", "Só cai se parar de pagar", "Só cai se for de shopping"],
        "answer": 1,
        "explanation": "Dividendos não impedem oscilação. O preço do FII varia com juros, vacância, mercado, confiança e expectativa de renda.",
    },
    {
        "id": "q_risco_001",
        "topic": "Risco",
        "difficulty": 1,
        "question": "Qual frase é mais correta sobre risco e retorno?",
        "options": ["Quanto maior o retorno, menor o risco", "Risco e retorno não se relacionam", "Maior potencial de retorno costuma vir com maior risco", "Risco só existe em ações"],
        "answer": 2,
        "explanation": "Em geral, ativos com mais retorno esperado têm mais risco (volatilidade, crédito, prazo, etc.).",
    },
    {
        "id": "q_div_001",
        "topic": "Diversificação",
        "difficulty": 2,
        "question": "Diversificar serve principalmente para:",
        "options": ["Garantir lucro sempre", "Reduzir risco específico (de um ativo/setor)", "Aumentar imposto", "Evitar estudar"],
        "answer": 1,
        "explanation": "Diversificação reduz risco específico, mas não elimina risco de mercado.",
    },
    {
        "id": "q_taxa_001",
        "topic": "Fundos/Taxas",
        "difficulty": 2,
        "question": "Por que taxa de administração importa no longo prazo?",
        "options": ["Porque aumenta o retorno", "Porque tira uma parte do rendimento todo ano", "Porque impede volatilidade", "Porque evita imposto"],
        "answer": 1,
        "explanation": "Taxas acumulam e podem comer uma parte grande do retorno com o tempo.",
    },
]
